# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.11

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.11.4/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.11.4/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/carla/git/icg/ICG2019/CG_TESTE_GPU

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/carla/git/icg/ICG2019/CG_TESTE_GPU

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.11.4/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.11.4/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.11.4/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.11.4/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.11.4/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.11.4/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.11.4/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.11.4/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/carla/git/icg/ICG2019/CG_TESTE_GPU/CMakeFiles /Users/carla/git/icg/ICG2019/CG_TESTE_GPU/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/carla/git/icg/ICG2019/CG_TESTE_GPU/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named openglexample

# Build rule for target.
openglexample: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 openglexample
.PHONY : openglexample

# fast build rule for target.
openglexample/fast:
	$(MAKE) -f CMakeFiles/openglexample.dir/build.make CMakeFiles/openglexample.dir/build
.PHONY : openglexample/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) -f libs/glfw/src/CMakeFiles/glfw.dir/build.make libs/glfw/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named glad

# Build rule for target.
glad: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glad
.PHONY : glad

# fast build rule for target.
glad/fast:
	$(MAKE) -f libs/glad/CMakeFiles/glad.dir/build.make libs/glad/CMakeFiles/glad.dir/build
.PHONY : glad/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) -f libs/glm/CMakeFiles/uninstall.dir/build.make libs/glm/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named glm_shared

# Build rule for target.
glm_shared: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glm_shared
.PHONY : glm_shared

# fast build rule for target.
glm_shared/fast:
	$(MAKE) -f libs/glm/glm/CMakeFiles/glm_shared.dir/build.make libs/glm/glm/CMakeFiles/glm_shared.dir/build
.PHONY : glm_shared/fast

#=============================================================================
# Target rules for targets named glm_static

# Build rule for target.
glm_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glm_static
.PHONY : glm_static

# fast build rule for target.
glm_static/fast:
	$(MAKE) -f libs/glm/glm/CMakeFiles/glm_static.dir/build.make libs/glm/glm/CMakeFiles/glm_static.dir/build
.PHONY : glm_static/fast

game/src/main.o: game/src/main.cpp.o

.PHONY : game/src/main.o

# target to build an object file
game/src/main.cpp.o:
	$(MAKE) -f CMakeFiles/openglexample.dir/build.make CMakeFiles/openglexample.dir/game/src/main.cpp.o
.PHONY : game/src/main.cpp.o

game/src/main.i: game/src/main.cpp.i

.PHONY : game/src/main.i

# target to preprocess a source file
game/src/main.cpp.i:
	$(MAKE) -f CMakeFiles/openglexample.dir/build.make CMakeFiles/openglexample.dir/game/src/main.cpp.i
.PHONY : game/src/main.cpp.i

game/src/main.s: game/src/main.cpp.s

.PHONY : game/src/main.s

# target to generate assembly for a file
game/src/main.cpp.s:
	$(MAKE) -f CMakeFiles/openglexample.dir/build.make CMakeFiles/openglexample.dir/game/src/main.cpp.s
.PHONY : game/src/main.cpp.s

game/src/shader.o: game/src/shader.cpp.o

.PHONY : game/src/shader.o

# target to build an object file
game/src/shader.cpp.o:
	$(MAKE) -f CMakeFiles/openglexample.dir/build.make CMakeFiles/openglexample.dir/game/src/shader.cpp.o
.PHONY : game/src/shader.cpp.o

game/src/shader.i: game/src/shader.cpp.i

.PHONY : game/src/shader.i

# target to preprocess a source file
game/src/shader.cpp.i:
	$(MAKE) -f CMakeFiles/openglexample.dir/build.make CMakeFiles/openglexample.dir/game/src/shader.cpp.i
.PHONY : game/src/shader.cpp.i

game/src/shader.s: game/src/shader.cpp.s

.PHONY : game/src/shader.s

# target to generate assembly for a file
game/src/shader.cpp.s:
	$(MAKE) -f CMakeFiles/openglexample.dir/build.make CMakeFiles/openglexample.dir/game/src/shader.cpp.s
.PHONY : game/src/shader.cpp.s

game/src/texture.o: game/src/texture.cpp.o

.PHONY : game/src/texture.o

# target to build an object file
game/src/texture.cpp.o:
	$(MAKE) -f CMakeFiles/openglexample.dir/build.make CMakeFiles/openglexample.dir/game/src/texture.cpp.o
.PHONY : game/src/texture.cpp.o

game/src/texture.i: game/src/texture.cpp.i

.PHONY : game/src/texture.i

# target to preprocess a source file
game/src/texture.cpp.i:
	$(MAKE) -f CMakeFiles/openglexample.dir/build.make CMakeFiles/openglexample.dir/game/src/texture.cpp.i
.PHONY : game/src/texture.cpp.i

game/src/texture.s: game/src/texture.cpp.s

.PHONY : game/src/texture.s

# target to generate assembly for a file
game/src/texture.cpp.s:
	$(MAKE) -f CMakeFiles/openglexample.dir/build.make CMakeFiles/openglexample.dir/game/src/texture.cpp.s
.PHONY : game/src/texture.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... openglexample"
	@echo "... glfw"
	@echo "... glad"
	@echo "... uninstall"
	@echo "... glm_shared"
	@echo "... glm_static"
	@echo "... game/src/main.o"
	@echo "... game/src/main.i"
	@echo "... game/src/main.s"
	@echo "... game/src/shader.o"
	@echo "... game/src/shader.i"
	@echo "... game/src/shader.s"
	@echo "... game/src/texture.o"
	@echo "... game/src/texture.i"
	@echo "... game/src/texture.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

